// Generated by spider on 2021-09-08 22:20:21.719642

part of 'resources.dart';

class IconsApp {
  IconsApp._();

  static const String card = 'res/icons/Card.png';
  static const String settings = 'res/icons/Settings.png';
  static const String unionBig = 'res/icons/UnionBig.png';
  static const String heartFull = 'res/icons/Heart Full.png';
  static const String map = 'res/icons/Map.png';
  static const String arrow = 'res/icons/Arrow.png';
  static const String list = 'res/icons/List.png';
  static const String heart = 'res/icons/Heart.png';
  static const String calendar = 'res/icons/Calendar.png';
  static const String union = 'res/icons/Union.png';
}
