// Generated by spider on 2021-09-03 16:11:33.571653

part of 'resources.dart';

class IconsApp {
  IconsApp._();

  static const String arrow = 'res/icons/Arrow.png';
  static const String heart = 'res/icons/Heart.png';
  static const String calendar = 'res/icons/Calendar.png';
  static const String union = 'res/icons/Union.png';
}
