// Generated by spider on 2021-09-03 15:31:52.020249

part of 'resources.dart';

class Svgs {
  Svgs._();

  static const String calendar = 'res/calendar.svg';
  static const String route = 'res/route.svg';
  static const String heart = 'res/heart.svg';
}
