// Generated by spider on 2021-09-03 16:11:33.740535

part of 'resources.dart';

class Svgs {
  Svgs._();

  static const String calendar = 'res/calendar.svg';
  static const String route = 'res/route.svg';
  static const String heart = 'res/heart.svg';
}
