// Generated by spider on 2021-09-03 15:19:41.089864

part of 'resources.dart';

class Svgs {
  Svgs._();

  static const String calendar = 'res/calendar.svg';
  static const String route = 'res/route.svg';
  static const String heart = 'res/heart.svg';
}
